import { Symptom, BodySystemCategory, BodySystem } from "@/types/symptoms";

export const bodySystems: BodySystemCategory[] = [
  {
    id: "head_neurological",
    name: "Head / Neurological",
    translations: {
      en: "Head / Neurological",
      hi: "सिर / तंत्रिका तंत्र",
      gu: "માથું / ચેતાં તંત્ર",
      mr: "डोके / तंत्रिका संस्था",
      bn: "মাথা / স্নাযুতন্ত্র",
      ta: "தலை / நரம்பு மண்டலம்",
      te: "తల / నాడీ వ్యవస్థ",
      kn: "ತಲೆ / ನರಮಂಡಲ",
      ml: "തല / നാഡീവ്യവസ്ഥ",
    },
    icon: "🧠",
    symptoms: [],
  },
  {
    id: "eyes",
    name: "Eyes",
    translations: {
      en: "Eyes",
      hi: "आंखें",
      gu: "આંખો",
      mr: "डोळे",
      bn: "চোখ",
      ta: "கண்கள்",
      te: "కళ్ళు",
      kn: "ಕಣ್ಣುಗಳು",
      ml: "കണ്ണുകൾ",
    },
    icon: "👁️",
    symptoms: [],
  },
  {
    id: "ent",
    name: "Ear / Nose / Throat",
    translations: {
      en: "Ear / Nose / Throat",
      hi: "कान / नाक / गला",
      gu: "કાન / નાક / ગળા",
      mr: "कान / नाक / घश",
      bn: "কান / নাক / গলা",
      ta: "செவி / மூக்கு / தொண்டை",
      te: "చెవి / ముక్కు / గొంతు",
      kn: "ಕಿವಿ / ಮೂಗು / ಗಂಟಲು",
      ml: "ചെവി / മൂക്ക് / തൊണ്ട",
    },
    icon: "👂",
    symptoms: [],
  },
  {
    id: "respiratory",
    name: "Breathing / Lungs",
    translations: {
      en: "Breathing / Lungs",
      hi: "सांस / फेफड़े",
      gu: "શ્વાસ / ફેફસાં",
      mr: "श्वासोच्छ्वास / फुफ्फुसे",
      bn: "শ্বাস / ফুসফুস",
      ta: "சுவாசம் / நுரையொரம்புகள்",
      te: "శ్వాస / ఊపిరితిత్తులు",
      kn: "ಉಸಿರಾಟ / ಶ್ವಾಸಕೋಶಗಳು",
      ml: "ശ്വാസം / ശ്വാസകോശങ്ങൾ",
    },
    icon: "🫁",
    symptoms: [],
  },
  {
    id: "cardiovascular",
    name: "Heart / Chest",
    translations: {
      en: "Heart / Chest",
      hi: "दिल / सीना",
      gu: "હૃદય / છાતી",
      mr: "हृदय / छाती",
      bn: "হার্ট / বুক",
      ta: "இதயம் / மார்பு",
      te: "గుండె / ఛాతీ",
      kn: "ಹೃದಯ / ಎದೆ",
      ml: "ഹൃദയം / നെഞ്ച്",
    },
    icon: "❤️",
    symptoms: [],
  },
  {
    id: "gastrointestinal",
    name: "Stomach / Digestion",
    translations: {
      en: "Stomach / Digestion",
      hi: "पेट / पाचन",
      gu: "પેટ / પચાસ",
      mr: "पोट / पचन",
      bn: "পেট / পাচন",
      ta: "வயிறு / செரிமானம்",
      te: "పొట్టు / జీర్ణక్రియ",
      kn: "ಹೊಟ್ಟೆ / ಜೀರ್ಣಕ್ರಿಯೆ",
      ml: "വയർ / ദഹനം",
    },
    icon: "🩺",
    symptoms: [],
  },
  {
    id: "musculoskeletal",
    name: "Bones / Joints / Muscles",
    translations: {
      en: "Bones / Joints / Muscles",
      hi: "हड्डियां / जोड़ / मांसपेशियां",
      gu: "હાડકાં / જોડાણ / સ્નાયુઓ",
      mr: "हाडे / सांधे / स्नायू",
      bn: "হাড় / জয়েন্ট / পেশি",
      ta: "எலும்புகள் / மூட்டுகள் / தசைகள்",
      te: "ఎముకలు / కీళ్ళు / కండరాలు",
      kn: "ಮೂಳೆಗಳು / ಕೀಲುಗಳು / ಸ್ನಾಯుಗಳು",
      ml: "എല്ലുകൾ / സന്ധികൾ / പേശികൾ",
    },
    icon: "🦴",
    symptoms: [],
  },
  {
    id: "skin",
    name: "Skin",
    translations: {
      en: "Skin",
      hi: "त्वचा",
      gu: "ત્વચા",
      mr: "त्वचा",
      bn: "ত্বক",
      ta: "தோல்",
      te: "చర్మం",
      kn: "ಚರ್ಮ",
      ml: "ചര്മം",
    },
    icon: "🧴",
    symptoms: [],
  },
  {
    id: "urinary",
    name: "Urinary / Kidney",
    translations: {
      en: "Urinary / Kidney",
      hi: "मूत्र / गुर्दा",
      gu: "મૂત્ર / કિડની",
      mr: "मूत्र / वृक्क",
      bn: "মূত্র / কিডনি",
      ta: "மூத்ரம் / சிறுநீரகம்",
      te: "మూత్రం / మూత్రపిండి",
      kn: "ಮೂತ್ರ / ಮೂತ್ರಪಿಂಡಗಳು",
      ml: "മൂത്രം / വൃക്ക",
    },
    icon: "🚻",
    symptoms: [],
  },
  {
    id: "mental_behavioral",
    name: "Mental / Behavioral",
    translations: {
      en: "Mental / Behavioral",
      hi: "मानसिक / व्यवहारिक",
      gu: "માનસિક / વર્તનાત્મક",
      mr: "मानसिक / वर्तन",
      bn: "মানসিক / আচরণগত",
      ta: "மன / நடத்தை",
      te: "మానసిక / ప్రవర్తన",
      kn: "ಮಾನಸಿಕ / ವರ್ತನೆ",
      ml: "മാനസിക / പെരുമാറ്റം",
    },
    icon: "🧠",
    symptoms: [],
  },
  {
    id: "general",
    name: "General Symptoms",
    translations: {
      en: "General Symptoms",
      hi: "सामान्य लक्षण",
      gu: "સામાન્ય લક્ષણો",
      mr: "सामान्य लक्षणे",
      bn: "সাধারণ লক্ষণ",
      ta: "பொது அறிகுறிகள்",
      te: "సాధారణ లక్షణాలు",
      kn: "ಸಾಮಾನ್ಯ ಲಕ್ಷಣಗಳು",
      ml: "പൊതു ലക്ഷണങ്ങൾ",
    },
    icon: "🌡️",
    symptoms: [],
  },
];

export const symptoms: Symptom[] = [
  // Head / Neurological
  {
    id: "headache",
    name: "Headache",
    translations: {
      en: "Headache",
      hi: "सिरदर्द",
      gu: "માથાનો દુખાવો",
      mr: "डोकेदुखी",
      bn: "মাথাব্যথা",
      ta: "தலைவலி",
      te: "తల నొప్పి",
      kn: "ತಲೆ ನೋವು",
      ml: "തലവേദന",
    },
    bodySystem: "head_neurological",
    bodyLocation: "head",
    relatedSymptoms: ["dizziness", "nausea", "vision_changes", "fatigue"],
    followUpQuestions: [
      {
        id: "headache_duration",
        question: "How long have you had the headache?",
        translations: {
          en: "How long have you had the headache?",
          hi: "आपको सिरदर्द कितने समय से है?",
          gu: "તમને માથાનો દુખાવો કેટલા સમયથી છે?",
          mr: "तुम्हाला डोकेदुखी किती वेळापासून आहे?",
          bn: "আপনার মাথাব্যথা কতক্ষণ ধরে হচ্ছে?",
          ta: "உங்களுக்கு தலைவலி எவ்வளவு நேரமாயிற்று?",
          te: "మీకు తల నొప్పి ఎంత కాలంగా ఉంది?",
          kn: "ನಿಮಗೆ ತಲೆ ನೋವು ಎಷ್ಟು ಸಮಯದಿಂದ ಇದೆ?",
          ml: "നിങ്ങൾക്ക് തലവേദന എത്ര നേരമായി?",
        },
        type: "duration",
        options: [
          { value: "less_1_day", label: "Less than 1 day", translations: { en: "Less than 1 day" } },
          { value: "1_3_days", label: "1-3 days", translations: { en: "1-3 days" } },
          { value: "4_7_days", label: "4-7 days", translations: { en: "4-7 days" } },
          { value: "1_2_weeks", label: "1-2 weeks", translations: { en: "1-2 weeks" } },
          { value: "more_2_weeks", label: "More than 2 weeks", translations: { en: "More than 2 weeks" } },
        ],
        required: true,
      },
      {
        id: "headache_severity",
        question: "How severe is the pain? (0-10)",
        translations: {
          en: "How severe is the pain? (0-10)",
          hi: "दर्द कितना गंभीर है? (0-10)",
          gu: "દુખાવો કેટલો ગંભીર છે? (0-10)",
          mr: "दुखी किती गंभीर आहे? (0-10)",
          bn: "ব্যথা কতটা তীব্র? (0-10)",
          ta: "வலி எவ்வளவு கடுமையானது? (0-10)",
          te: "నొప్పి ఎంత తీవ్రమైనది? (0-10)",
          kn: "ನೋವು ಎಷ್ಟು ತೀವ್ರವಾಗಿದೆ? (0-10)",
          ml: "വേദന എത്ര രൂക്ഷമാണ്? (0-10)",
        },
        type: "severity",
        required: true,
      },
      {
        id: "headache_location",
        question: "Where is the pain located?",
        translations: {
          en: "Where is the pain located?",
          hi: "दर्द कहां है?",
          gu: "દુખાવો ક્યાં છે?",
          mr: "दुखी कोठे आहे?",
          bn: "ব্যথা কোথায়?",
          ta: "வலி எங்கே உள்ளது?",
          te: "నొప్పి ఎక్కడ ఉంది?",
          kn: "ನೋವು ಎಲ್ಲಿದೆ?",
          ml: "വേദന എവിടെയാണ്?",
        },
        type: "location",
        options: [
          { value: "forehead", label: "Forehead", translations: { en: "Forehead" } },
          { value: "temples", label: "Temples (sides)", translations: { en: "Temples (sides)" } },
          { value: "back_of_head", label: "Back of head", translations: { en: "Back of head" } },
          { value: "one_side", label: "One side only", translations: { en: "One side only" } },
          { value: "all_over", label: "All over head", translations: { en: "All over head" } },
        ],
        required: true,
      },
      {
        id: "headache_character",
        question: "What does the pain feel like?",
        translations: {
          en: "What does the pain feel like?",
          hi: "दर्द कैसा महसूस होता है?",
          gu: "દુખાવો કેવો લાગે છે?",
          mr: "दुखी कशी वाटते?",
          bn: "ব্যথা কেমন অনুভূত হয়?",
          ta: "வலி எப்படி உணரப்படுகிறது?",
          te: "నొప్పి ఎలా అనిపిస్తుంది?",
          kn: "ನೋವು ಹೇಗೆ ಅನುಭವವಾಗುತ್ತೆ?",
          ml: "വേദന എങ്ങനെ അനുഭവപ്പെടുന്നു?",
        },
        type: "character",
        options: [
          { value: "pressure", label: "Pressure/tightness", translations: { en: "Pressure/tightness" } },
          { value: "throbbing", label: "Throbbing/pulsing", translations: { en: "Throbbing/pulsing" } },
          { value: "sharp", label: "Sharp/stabbing", translations: { en: "Sharp/stabbing" } },
          { value: "burning", label: "Burning", translations: { en: "Burning" } },
          { value: "dull_ache", label: "Dull ache", translations: { en: "Dull ache" } },
        ],
        required: true,
      },
      {
        id: "headache_triggers",
        question: "What makes it worse?",
        translations: {
          en: "What makes it worse?",
          hi: "क्या इसे बढ़ा देता है?",
          gu: "શું તેને વધારે ખરાબ બનાવે છે?",
          mr: "काय याला वाढवते?",
          bn: "কী এটাকে আরও খারাপ করে?",
          ta: "என்ன அதை மோசமாக்குகிறது?",
          te: "దీనిని తీవ్రంగా మార్చేది ఏమిటి?",
          kn: "ಇದನ್ನು ಹೆಚ್ಚು ಕೆಟ್ಟದಾಗಿಸುವುದು ಏನು?",
          ml: "എന്താണ് അതിനെ കൂടുതൽ മോശമാക്കുന്നത്?",
        },
        type: "triggers",
        options: [
          { value: "movement", label: "Movement", translations: { en: "Movement" } },
          { value: "light", label: "Light", translations: { en: "Light" } },
          { value: "noise", label: "Noise", translations: { en: "Noise" } },
          { value: "screen", label: "Screen use", translations: { en: "Screen use" } },
          { value: "food", label: "Certain foods", translations: { en: "Certain foods" } },
          { value: "stress", label: "Stress", translations: { en: "Stress" } },
        ],
        required: false,
      },
    ],
    priorityRules: [
      {
        condition: "severity >= 8",
        severity: "high",
        message: "Severe headache reported - may require immediate evaluation",
        translations: {
          en: "Severe headache reported - may require immediate evaluation",
        },
      },
      {
        condition: "duration > 2_weeks AND severity >= 6",
        severity: "medium",
        message: "Persistent severe headache - should be evaluated",
        translations: {
          en: "Persistent severe headache - should be evaluated",
        },
      },
    ],
  },
  {
    id: "dizziness",
    name: "Dizziness",
    translations: {
      en: "Dizziness",
      hi: "चक्कर आना",
      gu: "ભેરી આવવું",
      mr: "बसका येणे",
      bn: "মাথা ঘোরা",
      ta: "தலை சுற்று",
      te: "తల తిరగడం",
      kn: "ತಲೆ ಸುತ್ತುವುದು",
      ml: "തല കറങ്ങൽ",
    },
    bodySystem: "head_neurological",
    bodyLocation: "head",
    relatedSymptoms: ["headache", "nausea", "fainting", "weakness"],
    followUpQuestions: [
      {
        id: "dizziness_type",
        question: "What type of dizziness do you experience?",
        translations: {
          en: "What type of dizziness do you experience?",
          hi: "आपको किस प्रकार का चक्कर आता है?",
          gu: "તમને કઈ પ્રકારની ભેરી આવે છે?",
          mr: "तुम्हाला कोणत्या प्रकारची बसका येते?",
          bn: "আপনি কেমন ধরনের মাথা ঘোরা অনুভব করেন?",
          ta: "நீங்கள் எந்த வகையான தலை சுற்று அனுபவிக்கிறீர்கள்?",
          te: "మీకు ఏ రకం తల తిరగడం అనుభవం అవుతుంది?",
          kn: "ನಿಮಗೆ ಯಾವ ಬಗೆಯ ತಲೆ ಸುತ್ತುವುದು ಅನುಭವವಾಗುತ್ತೆ?",
          ml: "നിങ്ങൾക്ക് ഏത് തരം തല കറങ്ങൽ അനുഭവപ്പെടുന്നു?",
        },
        type: "custom",
        options: [
          { value: "spinning", label: "Spinning sensation", translations: { en: "Spinning sensation" } },
          { value: "lightheaded", label: "Lightheaded/faint", translations: { en: "Lightheaded/faint" } },
          { value: "off_balance", label: "Off balance", translations: { en: "Off balance" } },
          { value: "floating", label: "Floating sensation", translations: { en: "Floating sensation" } },
        ],
        required: true,
      },
      {
        id: "dizziness_triggers",
        question: "When does it happen?",
        translations: {
          en: "When does it happen?",
          hi: "यह कब होता है?",
          gu: "આ ક્યારે થાય છે?",
          mr: "हे कोठे होते?",
          bn: "এটা কখন হয়?",
          ta: "இது எப்போது நடக்கிறது?",
          te: "ఇది ఎప్పుడు జరుగుతుంది?",
          kn: "ಇದು ಯಾವಾಗ ಸಂಭವಿಸುತ್ತೆ?",
          ml: "ഇത് എപ്പോൾ സംഭവിക്കുന്നു?",
        },
        type: "triggers",
        options: [
          { value: "standing", label: "When standing up", translations: { en: "When standing up" } },
          { value: "moving_head", label: "When moving head", translations: { en: "When moving head" } },
          { value: "constant", label: "Constant", translations: { en: "Constant" } },
          { value: "episodes", label: "In episodes", translations: { en: "In episodes" } },
        ],
        required: true,
      },
    ],
    priorityRules: [
      {
        condition: "type == spinning AND triggers == standing",
        severity: "medium",
        message: "Positional vertigo - should be evaluated",
        translations: {
          en: "Positional vertigo - should be evaluated",
        },
      },
    ],
  },
  // Cardiovascular
  {
    id: "chest_pain",
    name: "Chest Pain",
    translations: {
      en: "Chest Pain",
      hi: "सीने में दर्द",
      gu: "છાતીમાં દુખાવો",
      mr: "छातीत दुखी",
      bn: "বুকে ব্যথা",
      ta: "மார்பு வலி",
      te: "ఛాతీ నొప్పి",
      kn: "ಎದೆ ನೋವು",
      ml: "നെഞ്ചു വേദന",
    },
    bodySystem: "cardiovascular",
    bodyLocation: "chest",
    relatedSymptoms: ["shortness_breath", "sweating", "nausea", "palpitations"],
    followUpQuestions: [
      {
        id: "chest_pain_location",
        question: "Where is the pain located?",
        translations: {
          en: "Where is the pain located?",
          hi: "दर्द कहां है?",
          gu: "દુખાવો ક્યાં છે?",
          mr: "दुखी कोठे आहे?",
          bn: "ব্যথা কোথায়?",
          ta: "வலி எங்கே உள்ளது?",
          te: "నొప్పి ఎక్కడ ఉంది?",
          kn: "ನೋವು ಎಲ್ಲಿದೆ?",
          ml: "വേദന എവിടെയാണ്?",
        },
        type: "location",
        options: [
          { value: "center", label: "Center of chest", translations: { en: "Center of chest" } },
          { value: "left_side", label: "Left side", translations: { en: "Left side" } },
          { value: "right_side", label: "Right side", translations: { en: "Right side" } },
          { value: "behind_breastbone", label: "Behind breastbone", translations: { en: "Behind breastbone" } },
        ],
        required: true,
      },
      {
        id: "chest_pain_character",
        question: "What does the pain feel like?",
        translations: {
          en: "What does the pain feel like?",
          hi: "दर्द कैसा महसूस होता है?",
          gu: "દુખાવો કેવો લાગે છે?",
          mr: "दुखी कशी वाटते?",
          bn: "ব্যথা কেমন অনুভূত হয়?",
          ta: "வலி எப்படி உணரப்படுகிறது?",
          te: "నొప్పి ఎలా అనిపిస్తుంది?",
          kn: "ನೋವು ಹೇಗೆ ಅನುಭವವಾಗುತ್ತೆ?",
          ml: "വേദന എങ്ങനെ അനുഭവപ്പെടുന്നു?",
        },
        type: "character",
        options: [
          { value: "pressure", label: "Pressure/squeezing", translations: { en: "Pressure/squeezing" } },
          { value: "burning", label: "Burning", translations: { en: "Burning" } },
          { value: "sharp", label: "Sharp/stabbing", translations: { en: "Sharp/stabbing" } },
          { value: "crushing", label: "Crushing", translations: { en: "Crushing" } },
        ],
        required: true,
      },
      {
        id: "chest_pain_severity",
        question: "How severe is the pain? (0-10)",
        translations: {
          en: "How severe is the pain? (0-10)",
          hi: "दर्द कितना गंभीर है? (0-10)",
          gu: "દુખાવો કેટલો ગંભીર છે? (0-10)",
          mr: "दुखी किती गंभीर आहे? (0-10)",
          bn: "ব্যথা কতটা তীব্র? (0-10)",
          ta: "வலி எவ்வளவு கடுமையானது? (0-10)",
          te: "నొప్పి ఎంత తీవ్రమైనది? (0-10)",
          kn: "ನೋವು ಎಷ್ಟು ತೀವ್ರವಾಗಿದೆ? (0-10)",
          ml: "വേദന എത്ര രൂക്ഷമാണ്? (0-10)",
        },
        type: "severity",
        required: true,
      },
    ],
    priorityRules: [
      {
        condition: "severity >= 7 AND character == pressure OR character == crushing",
        severity: "urgent",
        message: "Chest pain with pressure/crushing sensation - URGENT evaluation needed",
        translations: {
          en: "Chest pain with pressure/crushing sensation - URGENT evaluation needed",
        },
      },
      {
        condition: "severity >= 5",
        severity: "high",
        message: "Chest pain reported - requires prompt evaluation",
        translations: {
          en: "Chest pain reported - requires prompt evaluation",
        },
      },
    ],
  },
  // Respiratory
  {
    id: "shortness_breath",
    name: "Shortness of Breath",
    translations: {
      en: "Shortness of Breath",
      hi: "सांस की तकलीफ",
      gu: "શ્વાસની તકલીફ",
      mr: "श्वासावरोध",
      bn: "শ্বাসকষ্ট",
      ta: "மூச்சுத் திணறல்",
      te: "శ్వాస తీవ్రత",
      kn: "ಉಸಿರಾಟ ತೊಂದರೆ",
      ml: "ശ്വാസതടസ്സം",
    },
    bodySystem: "respiratory",
    bodyLocation: "chest",
    relatedSymptoms: ["chest_pain", "cough", "wheezing", "fatigue"],
    followUpQuestions: [
      {
        id: "sob_severity",
        question: "How severe is the breathing difficulty?",
        translations: {
          en: "How severe is the breathing difficulty?",
          hi: "सांस की तकलीफ कितनी गंभीर है?",
          gu: "શ્વાસની તકલીફ કેટલી ગંભીર છે?",
          mr: "श्वासावरोध किती गंभीर आहे?",
          bn: "শ্বাসকষ্ট কতটা তীব্র?",
          ta: "மூச்சுத் திணறல் எவ்வளவு கடுமையானது?",
          te: "శ్వాస తీవ్రత ఎంత తీవ్రమైనది?",
          kn: "ಉಸಿರಾಟ ತೊಂದರೆ ಎಷ್ಟು ತೀವ್ರವಾಗಿದೆ?",
          ml: "ശ്വാസതടസ്സം എത്ര രൂക്ഷമാണ്?",
        },
        type: "custom",
        options: [
          { value: "mild", label: "Mild - with exertion only", translations: { en: "Mild - with exertion only" } },
          { value: "moderate", label: "Moderate - affects daily activities", translations: { en: "Moderate - affects daily activities" } },
          { value: "severe", label: "Severe - at rest", translations: { en: "Severe - at rest" } },
        ],
        required: true,
      },
      {
        id: "sob_duration",
        question: "How long has this been going on?",
        translations: {
          en: "How long has this been going on?",
          hi: "यह कितने समय से चल रहा है?",
          gu: "આ કેટલા સમયથી ચાલી રહ્યું છે?",
          mr: "हे किती वेळापासून सुरू आहे?",
          bn: "এটা কতক্ষণ ধরে চলছে?",
          ta: "இது எவ்வளவு நேரமாயிற்று?",
          te: "ఇది ఎంత కాలంగా కొనసాగుతోంది?",
          kn: "ಇದು ಎಷ್ಟು ಸಮಯದಿಂದ ಮುಂದುವರಿಸುತ್ತಿದೆ?",
          ml: "ഇത് എത്ര നേരമായി തുടരുന്നു?",
        },
        type: "duration",
        options: [
          { value: "hours", label: "Hours", translations: { en: "Hours" } },
          { value: "days", label: "Days", translations: { en: "Days" } },
          { value: "weeks", label: "Weeks", translations: { en: "Weeks" } },
          { value: "months", label: "Months or longer", translations: { en: "Months or longer" } },
        ],
        required: true,
      },
    ],
    priorityRules: [
      {
        condition: "severity == severe",
        severity: "urgent",
        message: "Severe shortness of breath at rest - URGENT evaluation needed",
        translations: {
          en: "Severe shortness of breath at rest - URGENT evaluation needed",
        },
      },
      {
        condition: "severity == moderate",
        severity: "high",
        message: "Moderate breathing difficulty - requires prompt evaluation",
        translations: {
          en: "Moderate breathing difficulty - requires prompt evaluation",
        },
      },
    ],
  },
  // Gastrointestinal
  {
    id: "stomach_pain",
    name: "Stomach Pain",
    translations: {
      en: "Stomach Pain",
      hi: "पेट में दर्द",
      gu: "પેટમાં દુખાવો",
      mr: "पोटात दुखी",
      bn: "পেটে ব্যথা",
      ta: "வயிற்று வலி",
      te: "పొట్టు నొప్పి",
      kn: "ಹೊಟ್ಟೆ ನೋವು",
      ml: "വയർ വേദന",
    },
    bodySystem: "gastrointestinal",
    bodyLocation: "abdomen",
    relatedSymptoms: ["nausea", "vomiting", "diarrhea", "constipation"],
    followUpQuestions: [
      {
        id: "stomach_pain_location",
        question: "Where is the pain located?",
        translations: {
          en: "Where is the pain located?",
          hi: "दर्द कहां है?",
          gu: "દુખાવો ક્યાં છે?",
          mr: "दुखी कोठे आहे?",
          bn: "ব্যথা কোথায়?",
          ta: "வலி எங்கே உள்ளது?",
          te: "నొప్పి ఎక్కడ ఉంది?",
          kn: "ನೋವು ಎಲ್ಲಿದೆ?",
          ml: "വേദന എവിടെയാണ്?",
        },
        type: "location",
        options: [
          { value: "upper", label: "Upper abdomen", translations: { en: "Upper abdomen" } },
          { value: "lower", label: "Lower abdomen", translations: { en: "Lower abdomen" } },
          { value: "right_side", label: "Right side", translations: { en: "Right side" } },
          { value: "left_side", label: "Left side", translations: { en: "Left side" } },
          { value: "around_navel", label: "Around navel", translations: { en: "Around navel" } },
        ],
        required: true,
      },
      {
        id: "stomach_pain_character",
        question: "What does the pain feel like?",
        translations: {
          en: "What does the pain feel like?",
          hi: "दर्द कैसा महसूस होता है?",
          gu: "દુખાવો કેવો લાગે છે?",
          mr: "दुखी कशी वाटते?",
          bn: "ব্যথা কেমন অনুভূত হয়?",
          ta: "வலி எப்படி உணரப்படுகிறது?",
          te: "నొప్పి ఎలా అనిపిస్తుంది?",
          kn: "ನೋವು ಹೇಗೆ ಅನುಭವವಾಗುತ್ತೆ?",
          ml: "വേദന എങ്ങനെ അനുഭവപ്പെടുന്നു?",
        },
        type: "character",
        options: [
          { value: "burning", label: "Burning", translations: { en: "Burning" } },
          { value: "cramping", label: "Cramping", translations: { en: "Cramping" } },
          { value: "sharp", label: "Sharp", translations: { en: "Sharp" } },
          { value: "dull_ache", label: "Dull ache", translations: { en: "Dull ache" } },
          { value: "bloating", label: "Bloating pressure", translations: { en: "Bloating pressure" } },
        ],
        required: true,
      },
    ],
    priorityRules: [
      {
        condition: "location == right_side AND character == sharp",
        severity: "high",
        message: "Right-sided sharp abdominal pain - may indicate appendicitis",
        translations: {
          en: "Right-sided sharp abdominal pain - may indicate appendicitis",
        },
      },
    ],
  },
  // General
  {
    id: "fever",
    name: "Fever",
    translations: {
      en: "Fever",
      hi: "बुखार",
      gu: "તાવ",
      mr: "ज्वर",
      bn: "জ্বর",
      ta: "ஜ்வரம்",
      te: "జ్వరం",
      kn: "ಜ್ವರ",
      ml: "പനി",
    },
    bodySystem: "general",
    relatedSymptoms: ["chills", "sweating", "fatigue", "body_ache"],
    followUpQuestions: [
      {
        id: "fever_temperature",
        question: "What is your temperature?",
        translations: {
          en: "What is your temperature?",
          hi: "आपका तापमान क्या है?",
          gu: "તમારું તાપમાન કેટલું છે?",
          mr: "तुमचे तापमान किती आहे?",
          bn: "আপনার তাপমাত্রা কত?",
          ta: "உங்கள் வெப்பநிலை என்ன?",
          te: "మీ ఉష్ణోగ్రత ఎంత?",
          kn: "ನಿಮ್ಮ ತಾಪಮಾನ ಎಷ್ಟು?",
          ml: "നിങ്ങളുടെ താപനില എത്ര?",
        },
        type: "custom",
        options: [
          { value: "normal", label: "Normal (98.6°F/37°C)", translations: { en: "Normal (98.6°F/37°C)" } },
          { value: "low", label: "Low-grade (99-100°F)", translations: { en: "Low-grade (99-100°F)" } },
          { value: "moderate", label: "Moderate (100-102°F)", translations: { en: "Moderate (100-102°F)" } },
          { value: "high", label: "High (103°F or above)", translations: { en: "High (103°F or above)" } },
        ],
        required: true,
      },
      {
        id: "fever_duration",
        question: "How long have you had fever?",
        translations: {
          en: "How long have you had fever?",
          hi: "आपको बुखार कितने समय से है?",
          gu: "તમને તાવ કેટલા સમયથી છે?",
          mr: "तुम्हाला ज्वर किती वेळापासून आहे?",
          bn: "আপনার জ্বর কতক্ষণ ধরে হচ্ছে?",
          ta: "உங்களுக்கு ஜ்வரம் எவ்வளவு நேரமாயிற்று?",
          te: "మీకు జ్వరం ఎంత కాలంగా ఉంది?",
          kn: "ನಿಮಗೆ ಜ್ವರ ಎಷ್ಟು ಸಮಯದಿಂದ ಇದೆ?",
          ml: "നിങ്ങൾക്ക് പനി എത്ര നേരമായി?",
        },
        type: "duration",
        options: [
          { value: "hours", label: "Hours", translations: { en: "Hours" } },
          { value: "1_3_days", label: "1-3 days", translations: { en: "1-3 days" } },
          { value: "4_7_days", label: "4-7 days", translations: { en: "4-7 days" } },
          { value: "more_week", label: "More than a week", translations: { en: "More than a week" } },
        ],
        required: true,
      },
    ],
    priorityRules: [
      {
        condition: "temperature == high",
        severity: "high",
        message: "High fever - requires evaluation",
        translations: {
          en: "High fever - requires evaluation",
        },
      },
      {
        condition: "duration > 3_days AND temperature >= moderate",
        severity: "medium",
        message: "Persistent fever - should be evaluated",
        translations: {
          en: "Persistent fever - should be evaluated",
        },
      },
    ],
  },
];

export function getSymptomById(id: string): Symptom | undefined {
  return symptoms.find(s => s.id === id);
}

export function getSymptomsByBodySystem(system: BodySystem): Symptom[] {
  return symptoms.filter(s => s.bodySystem === system);
}

export function searchSymptoms(query: string, language: string = "en"): Symptom[] {
  const lowerQuery = query.toLowerCase();
  return symptoms.filter(s => 
    s.name.toLowerCase().includes(lowerQuery) ||
    s.translations[language]?.toLowerCase().includes(lowerQuery) ||
    s.relatedSymptoms.some(id => {
      const related = getSymptomById(id);
      return related?.name.toLowerCase().includes(lowerQuery) ||
             related?.translations[language]?.toLowerCase().includes(lowerQuery);
    })
  );
}